// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwAEjr62mQ3la71-3O-_9Ufpz-TLxUsXA',
    appId: '1:81844163034:web:779483f60ee61211c4b0e3',
    messagingSenderId: '81844163034',
    projectId: 'telephonyapplication',
    authDomain: 'telephonyapplication.firebaseapp.com',
    storageBucket: 'telephonyapplication.appspot.com',
    measurementId: 'G-PG7LYSQ6Z8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvy2xMnHiYjeF5DhGpN65kbEjwERGZ7Wg',
    appId: '1:81844163034:android:8b7dfedf60ac3eb2c4b0e3',
    messagingSenderId: '81844163034',
    projectId: 'telephonyapplication',
    storageBucket: 'telephonyapplication.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQnuGIyNIYrpbGTaZPL2aONpOkinGgmP4',
    appId: '1:81844163034:ios:4effdfecfcf675d6c4b0e3',
    messagingSenderId: '81844163034',
    projectId: 'telephonyapplication',
    storageBucket: 'telephonyapplication.appspot.com',
    iosBundleId: 'com.example.telephonApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQnuGIyNIYrpbGTaZPL2aONpOkinGgmP4',
    appId: '1:81844163034:ios:cafcc884f4796296c4b0e3',
    messagingSenderId: '81844163034',
    projectId: 'telephonyapplication',
    storageBucket: 'telephonyapplication.appspot.com',
    iosBundleId: 'com.example.telephonApplication.RunnerTests',
  );
}
